### ISSUE TITLE
Basic Usage Help

### ISSUE THREAD

**Issue by StevenTCramer** [frogonwheels/TC2Git#3]
@frogonwheels 
I am not a git expert as I use Plasticscm as my DVCS.  But I can import git repos.  So I want to get everything out of TC into a git repo.   But I can't seem to figure out how to do this.

my email is the same as my git hub username @gmail.com  any help would be greatly appreciated.

Thanks

**Comment by YerayAlonso** [comment]
I could build it with RAD XE but when I run it it fails to load C:\Projects\maps.txt
Some basic instructions would be appreciated.

**Comment by code-kot** [comment]
May be you should build it with Delphi 2010.

**Comment by stevejordi** [comment]
Hi,
I was able to build it with Delphi2010 but how the hell do you use it? I always get an unknown option.
Can you give sample tc2git command line examples?

**Comment by code-kot** [comment]
tc2git.exe username:password /C MyTCConnectionName MyTCRepositoryName "\" /O "D:\Projects\TCExport" /X "C:\Program Files (x86)\SmartGit\git\bin\git.exe"

**Comment by frogonwheels** [comment]
Sorry for the slow response:  There is basic help if you run it without parameters.  I've not had to touch TeamComherence for  years, and the computer that I had it on has been deprecated, so even my old batchfiles I used to run are gone.  Thanks to @code-kot  for the response.

**Comment by frogonwheels** [comment]
Oh @YerayAlonso  - possibly you missed the fact that it's a CLI project.  There's no gui.

**Comment by frogonwheels** [comment]
I've added some infor in the README.markdown including that nice example from @code-kot .
(Also made it easier to compile in XE8+)

**Comment by stevejordi** [comment]
Thanks for the clarification.
It works perfectly I was able to export my TeamCoherence into GIT...
An example: my connection is called "Local" (in TCClient), user is sjordi, password is toto, my project is in C:\my projects\iPadExif and the project in TeamCoherence is called "EXIF Date Changer".
I typed:
TC2Git.exe sjordi:toto /C local "Exif Date Changer" "\" /O "C:\My Projects\iPadExif" /X "c:\Program Files (x86)\Git\bin\git.exe"

Thanks a lot for your help and your tool.
If someone can't get the project to compile in Delphi2010, let me know and I can provide the exe.

**Comment by code-kot** [comment]
@stevejordi You should not use a folder where you checked out your TC repository as output folder for exported git repository. If you are exporting TC repository to a new git repository you should use a new empty folder for it. Like this:
_/O "C:\My Projects\iPadExif_TCExport"_
or
_/O "C:\My Projects\ExifDateChanger"_

**Comment by stevejordi** [comment]
Yeap, sorry. I made a mistake. Since it may copy files... you have to make it point to an empty destination directory. The original one is known by TeamCoherence, so no need to mention it.
