### ISSUE TITLE
This can only be built with Delphi 2009 and up...

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [frogonwheels/TC2Git#6]
Is there any chance of releasing it as a binary? I'd want to use it with an older codebase built with 7 and that's the compiler I have to work with. It just chokes on the generics.collections include.

**Comment by frogonwheels** [comment]
Did you still want this?

**Comment by frogonwheels** [comment]
Have confirmed by email that this is still required.
Have done a binary release (in releases).
